name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Generate
        uses: docker://ghcr.io/mileschou/hexo
        with:
          args: hexo d

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          personal_token: ${{ secrets.BLOG }}
          external_repository: casun18/casun18.github.io
          publish_branch: gh-pages  # default: gh-pages
          publish_dir: ./public