name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: renzhaosy/hexo-deploy-action@master
      env:
        PERSONAL_TOKEN: ${{ secrets.BLOG_TOKEN }}
        PUBLISH_REPOSITORY: casun18/casun18.github.io # The repository the action should deploy to.
        BRANCH: main  # The branch the action should deploy to.
        PUBLISH_DIR: ./public # The folder the action should deploy.